@api=http://localhost:3000

### tasks

### find
GET {{api}}/tasks

### finById
GET {{api}}/tasks/0

### create
POST {{api}}/tasks
Content-Type: application/json

{
    "title": "Titulo 1",
    "user": 0
}

### update
PATCH {{api}}/tasks/0
Content-Type: application/json

{
    "completed": true
}

### replace
PUT {{api}}/tasks/0
Content-Type: application/json

{
    "title": "Ejemplo 3"
}

### delete
DELETE {{api}}/tasks/1
