@api=http://localhost:3000

### users

### find
GET {{api}}/users

### finByEmail
GET {{api}}/users/example@test.com

### create
POST {{api}}/users
Content-Type: application/json

{
    "firstName": "Example 2",
    "email": "example2@test.com",
    "password": "123456",
    "roles": []
}

### update
PATCH {{api}}/users/0
Content-Type: application/json

{
    "lastName": "Test"
}

### replace
PUT {{api}}/users/0
Content-Type: application/json

{
}

### delete
DELETE {{api}}/users/0


### value
GET {{api}}/users/value
